/*
Nnef_EventExposure

NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PerformanceDataInfo Contains Performance Data Analytics related information collection.
type PerformanceDataInfo struct {
	AppId *Object `json:"appId,omitempty"`
	UeIpAddr *Object `json:"ueIpAddr,omitempty"`
	IpTrafficFilter *Object `json:"ipTrafficFilter,omitempty"`
	UserLoc *Object `json:"userLoc,omitempty"`
	AppLocs *[]Object `json:"appLocs,omitempty"`
	AsAddr *Object `json:"asAddr,omitempty"`
	PerfData Object `json:"perfData"`
	TimeStamp Object `json:"timeStamp"`
}

// NewPerformanceDataInfo instantiates a new PerformanceDataInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPerformanceDataInfo(perfData Object, timeStamp Object) *PerformanceDataInfo {
	this := PerformanceDataInfo{}
	this.PerfData = perfData
	this.TimeStamp = timeStamp
	return &this
}

// NewPerformanceDataInfoWithDefaults instantiates a new PerformanceDataInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPerformanceDataInfoWithDefaults() *PerformanceDataInfo {
	this := PerformanceDataInfo{}
	return &this
}

// GetAppId returns the AppId field value if set, zero value otherwise.
func (o *PerformanceDataInfo) GetAppId() Object {
	if o == nil || o.AppId == nil {
		var ret Object
		return ret
	}
	return *o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PerformanceDataInfo) GetAppIdOk() (*Object, bool) {
	if o == nil || o.AppId == nil {
		return nil, false
	}
	return o.AppId, true
}

// HasAppId returns a boolean if a field has been set.
func (o *PerformanceDataInfo) HasAppId() bool {
	if o != nil && o.AppId != nil {
		return true
	}

	return false
}

// SetAppId gets a reference to the given Object and assigns it to the AppId field.
func (o *PerformanceDataInfo) SetAppId(v Object) {
	o.AppId = &v
}

// GetUeIpAddr returns the UeIpAddr field value if set, zero value otherwise.
func (o *PerformanceDataInfo) GetUeIpAddr() Object {
	if o == nil || o.UeIpAddr == nil {
		var ret Object
		return ret
	}
	return *o.UeIpAddr
}

// GetUeIpAddrOk returns a tuple with the UeIpAddr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PerformanceDataInfo) GetUeIpAddrOk() (*Object, bool) {
	if o == nil || o.UeIpAddr == nil {
		return nil, false
	}
	return o.UeIpAddr, true
}

// HasUeIpAddr returns a boolean if a field has been set.
func (o *PerformanceDataInfo) HasUeIpAddr() bool {
	if o != nil && o.UeIpAddr != nil {
		return true
	}

	return false
}

// SetUeIpAddr gets a reference to the given Object and assigns it to the UeIpAddr field.
func (o *PerformanceDataInfo) SetUeIpAddr(v Object) {
	o.UeIpAddr = &v
}

// GetIpTrafficFilter returns the IpTrafficFilter field value if set, zero value otherwise.
func (o *PerformanceDataInfo) GetIpTrafficFilter() Object {
	if o == nil || o.IpTrafficFilter == nil {
		var ret Object
		return ret
	}
	return *o.IpTrafficFilter
}

// GetIpTrafficFilterOk returns a tuple with the IpTrafficFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PerformanceDataInfo) GetIpTrafficFilterOk() (*Object, bool) {
	if o == nil || o.IpTrafficFilter == nil {
		return nil, false
	}
	return o.IpTrafficFilter, true
}

// HasIpTrafficFilter returns a boolean if a field has been set.
func (o *PerformanceDataInfo) HasIpTrafficFilter() bool {
	if o != nil && o.IpTrafficFilter != nil {
		return true
	}

	return false
}

// SetIpTrafficFilter gets a reference to the given Object and assigns it to the IpTrafficFilter field.
func (o *PerformanceDataInfo) SetIpTrafficFilter(v Object) {
	o.IpTrafficFilter = &v
}

// GetUserLoc returns the UserLoc field value if set, zero value otherwise.
func (o *PerformanceDataInfo) GetUserLoc() Object {
	if o == nil || o.UserLoc == nil {
		var ret Object
		return ret
	}
	return *o.UserLoc
}

// GetUserLocOk returns a tuple with the UserLoc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PerformanceDataInfo) GetUserLocOk() (*Object, bool) {
	if o == nil || o.UserLoc == nil {
		return nil, false
	}
	return o.UserLoc, true
}

// HasUserLoc returns a boolean if a field has been set.
func (o *PerformanceDataInfo) HasUserLoc() bool {
	if o != nil && o.UserLoc != nil {
		return true
	}

	return false
}

// SetUserLoc gets a reference to the given Object and assigns it to the UserLoc field.
func (o *PerformanceDataInfo) SetUserLoc(v Object) {
	o.UserLoc = &v
}

// GetAppLocs returns the AppLocs field value if set, zero value otherwise.
func (o *PerformanceDataInfo) GetAppLocs() []Object {
	if o == nil || o.AppLocs == nil {
		var ret []Object
		return ret
	}
	return *o.AppLocs
}

// GetAppLocsOk returns a tuple with the AppLocs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PerformanceDataInfo) GetAppLocsOk() (*[]Object, bool) {
	if o == nil || o.AppLocs == nil {
		return nil, false
	}
	return o.AppLocs, true
}

// HasAppLocs returns a boolean if a field has been set.
func (o *PerformanceDataInfo) HasAppLocs() bool {
	if o != nil && o.AppLocs != nil {
		return true
	}

	return false
}

// SetAppLocs gets a reference to the given []Object and assigns it to the AppLocs field.
func (o *PerformanceDataInfo) SetAppLocs(v []Object) {
	o.AppLocs = &v
}

// GetAsAddr returns the AsAddr field value if set, zero value otherwise.
func (o *PerformanceDataInfo) GetAsAddr() Object {
	if o == nil || o.AsAddr == nil {
		var ret Object
		return ret
	}
	return *o.AsAddr
}

// GetAsAddrOk returns a tuple with the AsAddr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PerformanceDataInfo) GetAsAddrOk() (*Object, bool) {
	if o == nil || o.AsAddr == nil {
		return nil, false
	}
	return o.AsAddr, true
}

// HasAsAddr returns a boolean if a field has been set.
func (o *PerformanceDataInfo) HasAsAddr() bool {
	if o != nil && o.AsAddr != nil {
		return true
	}

	return false
}

// SetAsAddr gets a reference to the given Object and assigns it to the AsAddr field.
func (o *PerformanceDataInfo) SetAsAddr(v Object) {
	o.AsAddr = &v
}

// GetPerfData returns the PerfData field value
func (o *PerformanceDataInfo) GetPerfData() Object {
	if o == nil {
		var ret Object
		return ret
	}

	return o.PerfData
}

// GetPerfDataOk returns a tuple with the PerfData field value
// and a boolean to check if the value has been set.
func (o *PerformanceDataInfo) GetPerfDataOk() (*Object, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PerfData, true
}

// SetPerfData sets field value
func (o *PerformanceDataInfo) SetPerfData(v Object) {
	o.PerfData = v
}

// GetTimeStamp returns the TimeStamp field value
func (o *PerformanceDataInfo) GetTimeStamp() Object {
	if o == nil {
		var ret Object
		return ret
	}

	return o.TimeStamp
}

// GetTimeStampOk returns a tuple with the TimeStamp field value
// and a boolean to check if the value has been set.
func (o *PerformanceDataInfo) GetTimeStampOk() (*Object, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TimeStamp, true
}

// SetTimeStamp sets field value
func (o *PerformanceDataInfo) SetTimeStamp(v Object) {
	o.TimeStamp = v
}

func (o PerformanceDataInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AppId != nil {
		toSerialize["appId"] = o.AppId
	}
	if o.UeIpAddr != nil {
		toSerialize["ueIpAddr"] = o.UeIpAddr
	}
	if o.IpTrafficFilter != nil {
		toSerialize["ipTrafficFilter"] = o.IpTrafficFilter
	}
	if o.UserLoc != nil {
		toSerialize["userLoc"] = o.UserLoc
	}
	if o.AppLocs != nil {
		toSerialize["appLocs"] = o.AppLocs
	}
	if o.AsAddr != nil {
		toSerialize["asAddr"] = o.AsAddr
	}
	if true {
		toSerialize["perfData"] = o.PerfData
	}
	if true {
		toSerialize["timeStamp"] = o.TimeStamp
	}
	return json.Marshal(toSerialize)
}

type NullablePerformanceDataInfo struct {
	value *PerformanceDataInfo
	isSet bool
}

func (v NullablePerformanceDataInfo) Get() *PerformanceDataInfo {
	return v.value
}

func (v *NullablePerformanceDataInfo) Set(val *PerformanceDataInfo) {
	v.value = val
	v.isSet = true
}

func (v NullablePerformanceDataInfo) IsSet() bool {
	return v.isSet
}

func (v *NullablePerformanceDataInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePerformanceDataInfo(val *PerformanceDataInfo) *NullablePerformanceDataInfo {
	return &NullablePerformanceDataInfo{value: val, isSet: true}
}

func (v NullablePerformanceDataInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePerformanceDataInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


